
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa="",ha;document.currentScript&&(fa=document.currentScript.src);fa=0!==fa.indexOf("blob:")?fa.substr(0,fa.lastIndexOf("/")+1):"";ha=function(a){document.title=a};var ia=g.print||console.log.bind(console),k=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;
g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ja(a){ka||(ka={});ka[a]||(ka[a]=1,k(a))}var ka;function la(a,b){b&&b.length?g.dynCall_vi.apply(null,[a].concat(b)):g.dynCall_vi.call(null,a)}var ma;g.wasmBinary&&(ma=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&k("no native wasm support detected");
function na(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":l[a>>0]=b;break;case "i8":l[a>>0]=b;break;case "i16":oa[a>>1]=b;break;case "i32":p[a>>2]=b;break;case "i64":pa=[b>>>0,(r=b,1<=+qa(r)?0<r?(ra(+sa(r/4294967296),4294967295)|0)>>>0:~~+ta((r-+(~~r>>>0))/4294967296)>>>0:0)];p[a>>2]=pa[0];p[a+4>>2]=pa[1];break;case "float":t[a>>2]=b;break;case "double":v[a>>3]=b;break;default:x("invalid type for setValue: "+c)}}
var ua,va=new WebAssembly.Table({initial:577,maximum:577,element:"anyfunc"}),wa=!1;function xa(a,b){a||x("Assertion failed: "+b)}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?za(A,a,b):""}
function Aa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function B(a,b,c){return Aa(a,A,b,c)}
function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ca(a){var b=Ba(a)+1,c=C(b);c&&Aa(a,l,c,b);return c}function Da(a){var b=Ba(a)+1,c=Ea(b);Aa(a,l,c,b);return c}var Fa,l,A,oa,Ga,p,Ha,t,v,Ia=g.INITIAL_MEMORY||16777216;g.wasmMemory?ua=g.wasmMemory:ua=new WebAssembly.Memory({initial:Ia/65536,maximum:Ia/65536});ua&&(Fa=ua.buffer);Ia=Fa.byteLength;var E=Fa;
Fa=E;g.HEAP8=l=new Int8Array(E);g.HEAP16=oa=new Int16Array(E);g.HEAP32=p=new Int32Array(E);g.HEAPU8=A=new Uint8Array(E);g.HEAPU16=Ga=new Uint16Array(E);g.HEAPU32=Ha=new Uint32Array(E);g.HEAPF32=t=new Float32Array(E);g.HEAPF64=v=new Float64Array(E);p[22108]=5331472;function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.mf;"number"===typeof c?void 0===b.Me?g.dynCall_v(c):g.dynCall_vi(c,b.Me):c(void 0===b.Me?null:b.Me)}}}var Ka=[],La=[],Ma=[],Na=[],Oa=[];
function Pa(){var a=g.preRun.shift();Ka.unshift(a)}var qa=Math.abs,ta=Math.ceil,sa=Math.floor,ra=Math.min,Qa=0,Ra=null,Sa=null;g.preloadedImages={};g.preloadedAudios={};function x(a){if(g.onAbort)g.onAbort(a);ia(a);k(a);wa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ta(){var a=Ua;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ua="water.wasm";
if(!Ta()){var Va=Ua;Ua=g.locateFile?g.locateFile(Va,fa):fa+Va}function Wa(){try{if(ma)return new Uint8Array(ma);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function Xa(){return ma||"function"!==typeof fetch?new Promise(function(a){a(Wa())}):fetch(Ua,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ua+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}
var r,pa,Za={37852:function(a,b,c){g.SDL2||(g.SDL2={});var d=g.SDL2;d.Df!==g.canvas&&(d.ve=g.createContext(g.canvas,!1,!0),d.Df=g.canvas);if(d.Zf!==a||d.Kf!==b||d.Mf!==d.ve)d.image=d.ve.createImageData(a,b),d.Zf=a,d.Kf=b,d.Mf=d.ve;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=p[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.gg!==a&&(d.Ef=new Int32Array(a.buffer),d.Ff=new Uint8Array(a.buffer)),
a=d.Ef,c=a.length,a.set(p.subarray(b,b+c)),a=d.Ff,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ve.putImageData(d.image,0,0);return 0},39331:function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof
CanvasPixelArray)for(n=b.length;m<n;){var q=p[e];b[m]=q&255;b[m+1]=q>>8&255;b[m+2]=q>>16&255;b[m+3]=q>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(p.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=C(c.length+1);B(c,d,c.length+1);return d},40320:function(a){g.canvas&&(g.canvas.style.cursor=z(a));return 0},40413:function(){g.canvas&&(g.canvas.style.cursor="none")},41638:function(){return screen.width},
41665:function(){return screen.height},41693:function(){return window.innerWidth},41725:function(){return window.innerHeight},41803:function(a){"undefined"!==typeof ha&&ha(z(a));return 0},41937:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},42103:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},42329:function(a){"undefined"===
typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;a?b.capture={}:b.audio={};b.ne||("undefined"!==typeof AudioContext?b.ne=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ne=new webkitAudioContext));return void 0===b.ne?-1:0},42812:function(){return g.SDL2.ne.sampleRate},42882:function(a,b,c,d){function e(){}function f(m){void 0!==h.capture.Le&&(clearTimeout(h.capture.Le),h.capture.Le=void 0);h.capture.Oe=h.ne.createMediaStreamSource(m);h.capture.qe=h.ne.createScriptProcessor(b,a,1);h.capture.qe.onaudioprocess=
function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.We=n.inputBuffer,la(c,[d]))};h.capture.Oe.connect(h.capture.qe);h.capture.qe.connect(h.ne.destination);h.capture.stream=m}var h=g.SDL2;h.capture.Te=h.ne.createBuffer(a,b,h.ne.sampleRate);h.capture.Te.getChannelData(0).fill(0);h.capture.Le=setTimeout(function(){h.capture.We=h.capture.Te;la(c,[d])},b/h.ne.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},44534:function(a,b,c,d){var e=g.SDL2;e.audio.qe=e.ne.createScriptProcessor(b,0,a);e.audio.qe.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.hf=f.outputBuffer,la(c,[d]))};e.audio.qe.connect(e.ne.destination)},44944:function(a,b){for(var c=g.SDL2,d=c.capture.We.numberOfChannels,e=0;e<d;++e){var f=c.capture.We.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)na(a+4*h,f[h]);else for(h=0;h<b;++h)na(a+4*(h*d+e),f[h])}},45549:function(a,b){for(var c=g.SDL2,d=c.audio.hf.numberOfChannels,e=0;e<d;++e){var f=c.audio.hf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=t[a+(h*d+e<<2)>>2]}},46029:function(a){var b=g.SDL2;if(a){void 0!==b.capture.Le&&clearTimeout(b.capture.Le);
if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.qe&&(b.capture.qe.onaudioprocess=function(){},b.capture.qe.disconnect(),b.capture.qe=void 0);void 0!==b.capture.Oe&&(b.capture.Oe.disconnect(),b.capture.Oe=void 0);void 0!==b.capture.Te&&(b.capture.Te=void 0);b.capture=void 0}else void 0!=b.audio.qe&&(b.audio.qe.disconnect(),b.audio.qe=void 0),b.audio=void 0;void 0!==b.ne&&void 0===
b.audio&&void 0===b.capture&&(b.ne.close(),b.ne=void 0)}};La.push({mf:function(){$a()}});function ab(){p[bb()>>2]=28}function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function db(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var hb=[];function ib(a,b){hb[a]={input:[],pe:[],Fe:b};jb(a,kb)}
var kb={open:function(a){var b=hb[a.node.Se];if(!b)throw new F(43);a.me=b;a.seekable=!1},close:function(a){a.me.Fe.flush(a.me)},flush:function(a){a.me.Fe.flush(a.me)},read:function(a,b,c,d){if(!a.me||!a.me.Fe.nf)throw new F(60);for(var e=0,f=0;f<d;f++){try{var h=a.me.Fe.nf(a.me)}catch(m){throw new F(29);}if(void 0===h&&0===e)throw new F(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.me||!a.me.Fe.Ze)throw new F(60);try{for(var e=
0;e<d;e++)a.me.Fe.Ze(a.me,b[c+e])}catch(f){throw new F(29);}d&&(a.node.timestamp=Date.now());return e}},lb={nf:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(Ba(b)+1);b=Aa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},Ze:function(a,b){null===b||10===b?(ia(za(a.pe,0)),a.pe=[]):0!=b&&a.pe.push(b)},
flush:function(a){a.pe&&0<a.pe.length&&(ia(za(a.pe,0)),a.pe=[])}},mb={Ze:function(a,b){null===b||10===b?(k(za(a.pe,0)),a.pe=[]):0!=b&&a.pe.push(b)},flush:function(a){a.pe&&0<a.pe.length&&(k(za(a.pe,0)),a.pe=[])}},G={we:null,ye:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.we||(G.we={dir:{node:{Be:G.je.Be,xe:G.je.xe,He:G.je.He,Pe:G.je.Pe,yf:G.je.yf,Bf:G.je.Bf,zf:G.je.zf,xf:G.je.xf,Ue:G.je.Ue},stream:{Ee:G.ke.Ee}},
file:{node:{Be:G.je.Be,xe:G.je.xe},stream:{Ee:G.ke.Ee,read:G.ke.read,write:G.ke.write,cf:G.ke.cf,sf:G.ke.sf,uf:G.ke.uf}},link:{node:{Be:G.je.Be,xe:G.je.xe,Ke:G.je.Ke},stream:{}},gf:{node:{Be:G.je.Be,xe:G.je.xe},stream:nb}});c=ob(a,b,c,d);16384===(c.mode&61440)?(c.je=G.we.dir.node,c.ke=G.we.dir.stream,c.ie={}):32768===(c.mode&61440)?(c.je=G.we.file.node,c.ke=G.we.file.stream,c.le=0,c.ie=null):40960===(c.mode&61440)?(c.je=G.we.link.node,c.ke=G.we.link.stream):8192===(c.mode&61440)&&(c.je=G.we.gf.node,
c.ke=G.we.gf.stream);c.timestamp=Date.now();a&&(a.ie[b]=c);return c},jg:function(a){if(a.ie&&a.ie.subarray){for(var b=[],c=0;c<a.le;++c)b.push(a.ie[c]);return b}return a.ie},kg:function(a){return a.ie?a.ie.subarray?a.ie.subarray(0,a.le):new Uint8Array(a.ie):new Uint8Array(0)},jf:function(a,b){var c=a.ie?a.ie.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ie,a.ie=new Uint8Array(b),0<a.le&&a.ie.set(c.subarray(0,a.le),0))},Uf:function(a,b){if(a.le!=b)if(0==b)a.ie=
null,a.le=0;else{if(!a.ie||a.ie.subarray){var c=a.ie;a.ie=new Uint8Array(b);c&&a.ie.set(c.subarray(0,Math.min(b,a.le)))}else if(a.ie||(a.ie=[]),a.ie.length>b)a.ie.length=b;else for(;a.ie.length<b;)a.ie.push(0);a.le=b}},je:{Be:function(a){var b={};b.hg=8192===(a.mode&61440)?a.id:1;b.ng=a.id;b.mode=a.mode;b.tg=1;b.uid=0;b.lg=0;b.Se=a.Se;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.le:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.bg=new Date(a.timestamp);b.sg=new Date(a.timestamp);
b.fg=new Date(a.timestamp);b.Cf=4096;b.cg=Math.ceil(b.size/b.Cf);return b},xe:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.Uf(a,b.size)},He:function(){throw pb[44];},Pe:function(a,b,c,d){return G.createNode(a,b,c,d)},yf:function(a,b,c){if(16384===(a.mode&61440)){try{var d=qb(b,c)}catch(f){}if(d)for(var e in d.ie)throw new F(55);}delete a.parent.ie[a.name];a.name=c;b.ie[c]=a;a.parent=b},Bf:function(a,b){delete a.ie[b]},zf:function(a,
b){var c=qb(a,b),d;for(d in c.ie)throw new F(55);delete a.ie[b]},xf:function(a){var b=[".",".."],c;for(c in a.ie)a.ie.hasOwnProperty(c)&&b.push(c);return b},Ue:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},Ke:function(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},ke:{read:function(a,b,c,d,e){var f=a.node.ie;if(e>=a.node.le)return 0;a=Math.min(a.node.le-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,
c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ie||a.ie.subarray)){if(f)return a.ie=b.subarray(c,c+d),a.le=d;if(0===a.le&&0===e)return a.ie=b.slice(c,c+d),a.le=d;if(e+d<=a.le)return a.ie.set(b.subarray(c,c+d),e),d}G.jf(a,e+d);if(a.ie.subarray&&b.subarray)a.ie.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ie[e+f]=b[c+f];a.le=Math.max(a.le,e+d);return d},Ee:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.le);if(0>b)throw new F(28);return b},
cf:function(a,b,c){G.jf(a.node,b+c);a.node.le=Math.max(a.node.le,b+c)},sf:function(a,b,c,d,e,f,h){if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.ie;if(h&2||a.buffer!==b.buffer){if(0<e||e+d<a.length)a.subarray?a=a.subarray(e,e+d):a=Array.prototype.slice.call(a,e,e+d);e=!0;h=b.buffer==l.buffer;d=C(d);if(!d)throw new F(48);(h?l:b).set(a,d)}else e=!1,d=a.byteOffset;return{wg:d,ag:e}},uf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);if(e&2)return 0;G.ke.write(a,b,0,d,c,!1);
return 0}}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,xb={},F=null,pb={};
function yb(a,b){a=gb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={lf:!0,$e:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.$e)throw new F(32);a=cb(a.split("/").filter(function(h){return!!h}),!1);var e=rb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=qb(e,a[d]);c=db(c+"/"+a[d]);e.Qe&&(!f||f&&b.lf)&&(e=e.Qe.root);if(!f||b.kf)for(f=0;40960===(e.mode&61440);)if(e=zb(c),c=gb(eb(c),e),e=yb(c,{$e:b.$e}).node,40<f++)throw new F(32);}return{path:c,node:e}}
function Ab(a){for(var b;;){if(a===a.parent)return a=a.ye.tf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Bb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length}function qb(a,b){var c;if(c=(c=Cb(a,"x"))?c:a.je.He?0:2)throw new F(c,a);for(c=vb[Bb(a.id,b)];c;c=c.Rf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.je.He(a,b)}
function ob(a,b,c,d){a=new Db(a,b,c,d);b=Bb(a.parent.id,a.name);a.Rf=vb[b];return vb[b]=a}var Eb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Fb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cb(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Gb(a,b){try{return qb(a,b),20}catch(c){}return Cb(a,"wx")}function Hb(a){var b=4096;for(a=a||0;a<=b;a++)if(!tb[a])return a;throw new F(33);}function Ib(a,b){Jb||(Jb=function(){},Jb.prototype={});var c=new Jb,d;for(d in a)c[d]=a[d];a=c;b=Hb(b);a.Ae=b;return tb[b]=a}var nb={open:function(a){a.ke=sb[a.node.Se].ke;a.ke.open&&a.ke.open(a)},Ee:function(){throw new F(70);}};function jb(a,b){sb[a]={ke:b}}
function Kb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new F(10);if(!c&&!d){var e=yb(b,{lf:!1});b=e.path;e=e.node;if(e.Qe)throw new F(10);if(16384!==(e.mode&61440))throw new F(54);}b={type:a,vg:{},tf:b,Qf:[]};a=a.ye(b);a.ye=b;b.root=a;c?rb=a:e&&(e.Qe=b,e.ye&&e.ye.Qf.push(b))}function Lb(a,b,c){var d=yb(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new F(28);var e=Gb(d,a);if(e)throw new F(e);if(!d.je.Pe)throw new F(63);return d.je.Pe(d,a,b,c)}function H(a){Lb(a,16895,0)}
function Mb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Lb(a,b|8192,c)}function Nb(a,b){if(!gb(a))throw new F(44);var c=yb(b,{parent:!0}).node;if(!c)throw new F(44);b=fb(b);var d=Gb(c,b);if(d)throw new F(d);if(!c.je.Ue)throw new F(63);c.je.Ue(c,b,a)}function zb(a){a=yb(a).node;if(!a)throw new F(44);if(!a.je.Ke)throw new F(28);return gb(Ab(a.parent),a.je.Ke(a))}
function Ob(a,b,c,d){if(""===a)throw new F(44);if("string"===typeof b){var e=Eb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=db(a);try{f=yb(a,{kf:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(f){if(b&128)throw new F(20);}else f=Lb(a,c,0),e=!0;if(!f)throw new F(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new F(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Fb(b)||b&512)?31:Cb(f,Fb(b)):44))throw new F(c);if(b&512){c=f;var h;"string"===typeof c?h=yb(c,{kf:!0}).node:h=c;if(!h.je.xe)throw new F(63);if(16384===(h.mode&61440))throw new F(31);if(32768!==(h.mode&61440))throw new F(28);if(c=Cb(h,"w"))throw new F(c);h.je.xe(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Ib({node:f,path:Ab(f),flags:b,seekable:!0,position:0,ke:f.ke,Xf:[],error:!1},d);d.ke.open&&d.ke.open(d);!g.logReadFiles||b&1||(Pb||(Pb={}),a in Pb||(Pb[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{xb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),xb.onOpenFile(a,f))}catch(m){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Qb(a,b,c){if(null===a.Ae)throw new F(8);if(!a.seekable||!a.ke.Ee)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.ke.Ee(a,b,c);a.Xf=[]}
function Rb(){F||(F=function(a,b){this.node=b;this.Vf=function(c){this.De=c};this.Vf(a);this.message="FS error"},F.prototype=Error(),F.prototype.constructor=F,[44].forEach(function(a){pb[a]=new F(a);pb[a].stack="<generic error, no stack>"}))}var Sb;function Tb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ub(a,b,c){a=db("/dev/"+a);var d=Tb(!!b,!!c);Vb||(Vb=64);var e=Vb++<<8|0;jb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,m,n){for(var q=0,u=0;u<n;u++){try{var w=b()}catch(D){throw new F(29);}if(void 0===w&&0===q)throw new F(6);if(null===w||void 0===w)break;q++;h[m+u]=w}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,m,n){for(var q=0;q<n;q++)try{c(h[m+q])}catch(u){throw new F(29);}n&&(f.node.timestamp=Date.now());return q}});
Mb(a,d,e)}var Vb,Wb={},Jb,Pb,Xb=void 0;function Yb(){Xb+=4;return p[Xb-4>>2]}function Zb(a){a=tb[a];if(!a)throw new F(8);return a}var $b;$b=function(){return performance.now()};
function ac(a,b){bc=a;cc=b;if(dc)if(0==a)ec=function(){var d=Math.max(0,fc+b-$b())|0;setTimeout(gc,d)};else if(1==a)ec=function(){hc(gc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}ec=function(){setImmediate(gc)}}}
function ic(a,b,c,d,e){noExitRuntime=!0;xa(!dc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");dc=a;jc=d;var f="undefined"!==typeof d?function(){g.dynCall_vi(a,d)}:function(){g.dynCall_v(a)};var h=kc;gc=function(){if(!wa)if(0<lc.length){var m=Date.now(),n=lc.shift();n.mf(n.Me);if(mc){var q=mc,u=0==q%1?q-1:Math.floor(q);mc=n.eg?u:(8*q+(u+.5))/9}console.log('main loop blocker "'+
n.name+'" took '+(Date.now()-m)+" ms");g.setStatus&&(m=g.statusMessage||"Please wait...",n=mc,q=nc.ig,n?n<q?g.setStatus(m+" ("+(q-n)+"/"+q+")"):g.setStatus(m):g.setStatus(""));h<kc||setTimeout(gc,0)}else if(!(h<kc))if(oc=oc+1|0,1==bc&&1<cc&&0!=oc%cc)ec();else{0==bc&&(fc=$b());a:if(!(wa||g.preMainLoop&&!1===g.preMainLoop())){try{f()}catch(w){if(w instanceof pc)break a;w&&"object"===typeof w&&w.stack&&k("exception thrown: "+[w,w.stack]);throw w;}g.postMainLoop&&g.postMainLoop()}h<kc||("object"===typeof SDL&&
SDL.audio&&SDL.audio.Tf&&SDL.audio.Tf(),ec())}};e||(b&&0<b?ac(0,1E3/b):ac(1,1),ec());if(c)throw"unwind";}var ec=null,kc=0,dc=null,jc=0,bc=0,cc=0,oc=0,lc=[],nc={},fc,gc,mc,qc=!1,rc=!1,sc=[];
function tc(){function a(){rc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!uc){uc=!0;try{vc=!0}catch(c){vc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}wc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:vc?null:console.log("warning: no BlobBuilder");
xc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.vf||"undefined"!==typeof xc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.vf=!0);g.preloadPlugins.push({canHandle:function(c){return!g.vf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(vc)try{h=new Blob([c],{type:yc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:yc(d)}))}catch(q){ja("Blob constructor present but fails: "+
q+"; falling back to blob builder")}h||(h=new wc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=xc.createObjectURL(h),n=new Image;n.onload=function(){xa(n.complete,"Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);g.preloadedImages[d]=q;xc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});g.preloadPlugins.push({canHandle:function(c){return!g.ug&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(w){n||(n=!0,g.preloadedAudios[d]=w,e&&e(c))}function m(){n||(n=!0,g.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(vc){try{var q=new Blob([c],{type:yc(d)})}catch(w){return m()}q=xc.createObjectURL(q);var u=new Audio;u.addEventListener("canplaythrough",function(){h(u)},!1);u.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var w="",D=0,y=0,
O=0;O<c.length;O++)for(D=D<<8|c[O],y+=8;6<=y;){var P=D>>y-6&63;y-=6;w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[P]}2==y?(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(D&3)<<4],w+="=="):4==y&&(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(D&15)<<2],w+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+w;h(u)}};u.src=q;zc(function(){h(u)})}else return m()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!rc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ac(a,b,c,d){if(b&&g.ve&&a==g.canvas)return g.ve;var e;if(b){var f={antialias:!1,alpha:!1,rf:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof Bc&&(e=Cc(a,f)))var m=I[e].ze}else m=a.getContext("2d");if(!m)return null;c&&(b||xa("undefined"===typeof J,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.ve=m,b&&Dc(e),g.Yf=b,sc.forEach(function(n){n()}),tc());return m}var Ec=!1,Fc=void 0,Gc=void 0;
function Hc(a,b){function c(){qc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ic,Fc&&d.requestPointerLock(),qc=!0,Gc?("undefined"!=typeof SDL&&(p[SDL.screen>>2]=Ha[SDL.screen>>2]|8388608),Jc(g.canvas),Kc()):Jc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Gc?("undefined"!=typeof SDL&&(p[SDL.screen>>2]=Ha[SDL.screen>>2]&
-8388609),Jc(g.canvas),Kc()):Jc(d));if(g.onFullScreen)g.onFullScreen(qc);if(g.onFullscreen)g.onFullscreen(qc)}Fc=a;Gc=b;"undefined"===typeof Fc&&(Fc=!0);"undefined"===typeof Gc&&(Gc=!1);var d=g.canvas;Ec||(Ec=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Ic(){if(!qc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Lc=0;function hc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Lc)Lc=b+1E3/60;else for(;b+2>=Lc;)Lc+=1E3/60;setTimeout(a,Math.max(Lc-b,0))}}function zc(a){noExitRuntime=!0;setTimeout(function(){wa||a()},1E4)}
function yc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Mc=[];function Kc(){var a=g.canvas;Mc.forEach(function(b){b(a.width,a.height)})}
function Jc(a,b,c){b&&c?(a.$f=b,a.Lf=c):(b=a.$f,c=a.Lf);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Gc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var uc,vc,wc,xc,K=12288,Nc=!1,Oc=0,Pc=0,Qc=0,L={alpha:!1,depth:!1,stencil:!1,antialias:!1},Rc={},Sc;function Tc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Uc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Vc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Wc=1,Xc=0,Yc=[],M=[],Zc=[],$c=[],ad=[],N=[],Q=[],bd=[],I=[],cd=null,R=[],dd={},ed={},fd=4;function S(a){Xc||(Xc=a)}function gd(a){for(var b=Wc++,c=a.length;c<b;c++)a[c]=null;return b}var hd=[0],id=[0];function Cc(a,b){if(a=a.getContext("webgl",b)){var c=gd(I),d={mg:c,attributes:b,version:b.rf,ze:a};a.canvas&&(a.canvas.Ge=d);I[c]=d;("undefined"===typeof b.Hf||b.Hf)&&jd(d);b=c}else b=0;return b}function Dc(a){cd=I[a];g.ve=J=cd&&cd.ze}
function jd(a){a||(a=cd);if(!a.Nf){a.Nf=!0;var b=a.ze;Tc(b);Uc(b);Vc(b);b.te=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Bc={},kd,ld,md=0,nd=0,T=0,od=0,pd=0,qd=0,rd=0,sd=0,td=0,ud=null,vd=null,wd=null,xd=!1;function yd(){for(var a=U.length-1;0<=a;--a)zd(a);U=[];V=[]}var V=[];function Ad(a,b,c){function d(h,m){if(h.length!=m.length)return!1;for(var n in h)if(h[n]!=m[n])return!1;return!0}for(var e in V){var f=V[e];if(f.bf==a&&d(f.df,c))return}V.push({bf:a,wf:b,df:c});V.sort(function(h,m){return h.wf<m.wf})}
function Bd(a){for(var b=0;b<V.length;++b)V[b].bf==a&&(V.splice(b,1),--b)}function Cd(){if(Dd&&Ed.Ce)for(var a=0;a<V.length;++a){var b=V[a];V.splice(a,1);--a;b.bf.apply(null,b.df)}}var Dd=0,Ed=null,U=[];function zd(a){var b=U[a];b.target.removeEventListener(b.oe,b.If,b.re);U.splice(a,1)}
function W(a){function b(d){++Dd;Ed=a;Cd();a.ue(d);Cd();--Dd}if(a.se)a.If=b,a.target.addEventListener(a.oe,b,a.re),U.push(a),xd||(Na.push(yd),xd=!0);else for(var c=0;c<U.length;++c)U[c].target==a.target&&U[c].oe==a.oe&&zd(c--)}function Fd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Gd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Hd={},Id,Jd,Kd={},Ld=[0,document,window];
function X(a){a=2<a?z(a):a;return Ld[a]||document.querySelector(a)}function Md(a){var b=Nd(),c=Ea(8),d=c+4,e=Ea(a.id.length+1);B(a.id,e,a.id.length+1);if(a=X(e))p[c>>2]=a.width,p[d>>2]=a.height;c=[p[c>>2],p[d>>2]];Od(b);return c}function Pd(a,b,c){a=X(a);if(!a)return-4;a.width=b;a.height=c;return 0}function Qd(a,b,c){if(a.dg){var d=Nd(),e=Ea(a.id.length+1);B(a.id,e,a.id.length+1);Pd(e,b,c);Od(d)}else a.width=b,a.height=c}
function Rd(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Qd(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=u,a.style.paddingTop=w,a.style.paddingBottom=D,a.style.marginLeft=y,a.style.marginRight=
O,a.style.marginTop=P,a.style.marginBottom=Ya,document.body.style.margin=xe,document.documentElement.style.overflow=ye,document.body.scroll=ze,a.style.qf=Ae,a.Ge&&a.Ge.ze.viewport(0,0,d,e),Kd.Ne&&Y(Kd.Ne,37,0,Kd.ef))}var c=Md(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,u=a.style.paddingRight,w=a.style.paddingTop,D=a.style.paddingBottom,y=a.style.marginLeft,O=a.style.marginRight,P=a.style.marginTop,Ya=a.style.marginBottom,
xe=document.body.style.margin,ye=document.documentElement.style.overflow,ze=document.body.scroll,Ae=a.style.qf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Sd(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Td(a){return 0>Ld.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ud(a,b){if(0!=b.af||0!=b.Ve){Rd(a);var c=b.Wf?innerWidth:screen.width,d=b.Wf?innerHeight:screen.height,e=Td(a),f=e.width;e=e.height;var h=Md(a),m=h[0];h=h[1];3==b.af?(Sd(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.af&&(c*h<m*d?(f=h*c/m,Sd(a,(d-f)/2,0),d=f):(f=m*d/h,Sd(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Jf&&(a.style.qf="pixelated");
f=2==b.Ve?devicePixelRatio:1;0!=b.Ve&&(c=c*f|0,d=d*f|0,Qd(a,c,d),a.Ge&&a.Ge.ze.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Gd()?-3:-1;Kd=b;b.Ne&&Y(b.Ne,37,0,b.ef);return 0}function Vd(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Re)a.Re();else return document.body.requestPointerLock||document.body.Re?-3:-1;return 0}
function Wd(a,b){v[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)v[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)v[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)p[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];p[a+1296>>2]=b.connected;p[a+1300>>2]=b.index;p[a+8>>2]=b.axes.length;p[a+12>>2]=b.buttons.length;B(b.id,a+1304,64);B(b.mapping,a+1368,64)}var Xd=[];
function Yd(a,b,c,d){for(var e=0;e<a;e++){var f=J[c](),h=f&&gd(d);f?(f.name=h,d[h]=f):S(1282);p[b+4*e>>2]=h}}function Zd(a,b){Ha[a>>2]=b;Ha[a+4>>2]=(b-Ha[a>>2])/4294967296}
function $d(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&S(1280);return;case 36345:d=0;break;case 34466:var e=J.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=J.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":S(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:S(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:p[b+4*a>>2]=e[a];break;case 2:t[b+4*a>>2]=e[a];break;case 4:l[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){S(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:S(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Zd(b,
d);break;case 0:p[b>>2]=d;break;case 2:t[b>>2]=d;break;case 4:l[b>>0]=d?1:0}}else S(1281)}function ae(a){var b=Ba(a)+1,c=C(b);B(a,c,b);return c}
function be(a,b,c,d){if(c)if(a=J.getUniform(M[a],N[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:p[c>>2]=a;break;case 2:t[c>>2]=a;break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:p[c+4*b>>2]=a[b];break;case 2:t[c+4*b>>2]=a[b];break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else S(1281)}
function ce(a,b,c,d){if(c)if(a=J.getVertexAttrib(a,b),34975==b)p[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:p[c>>2]=a;break;case 2:t[c>>2]=a;break;case 5:p[c>>2]=Math.fround(a);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:p[c+4*b>>2]=a[b];break;case 2:t[c+4*b>>2]=a[b];break;case 5:p[c+4*b>>2]=Math.fround(a[b]);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+
d;}else S(1281)}function de(a,b,c,d,e){a-=5120;a=1==a?A:4==a?p:6==a?t:5==a||28922==a?Ha:Ga;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=fd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}function ee(a,b){if(!Gd())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Dd&&Ed.Ce?Ud(a,b):b.Gf?(Ad(Ud,1,[a,b]),1):-2:-3:-4}
function fe(a,b){var c={target:X(2),oe:"beforeunload",se:b,ue:function(d){d=d||event;var e=Y(b,28,0,a);e&&(e=z(e));if(e)return d.preventDefault(),d.returnValue=e},re:!0};W(c)}function ge(a,b,c,d,e,f){pd||(pd=C(256));a={target:X(a),oe:f,se:d,ue:function(h){h=h||event;var m=h.target.id?h.target.id:"",n=pd;B(Fd(h.target),n+0,128);B(m,n+128,128);Y(d,e,n,b)&&h.preventDefault()},re:c};W(a)}
function he(a,b,c,d,e){qd||(qd=C(280));W({target:a,oe:e,se:d,ue:function(f){f=f||event;var h=qd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;p[h>>2]=n;p[h+4>>2]=Gd();var q=n?m:ud,u=q&&q.id?q.id:"";B(Fd(q),h+8,128);B(u,h+136,128);p[h+264>>2]=q?q.clientWidth:0;p[h+268>>2]=q?q.clientHeight:0;p[h+272>>2]=screen.width;p[h+276>>2]=screen.height;n&&(ud=m);Y(d,19,h,b)&&f.preventDefault()},re:c})}
function ie(a,b,c,d,e){Jd||(Jd=C(1432));b={target:X(2),Ce:!0,oe:e,se:c,ue:function(f){f=f||event;var h=Jd;Wd(h,f.gamepad);Y(c,d,h,a)&&f.preventDefault()},re:b};W(b)}
function je(a,b,c,d,e,f){md||(md=C(164));a={target:X(a),Ce:!0,oe:f,se:d,ue:function(h){h=h||event;var m=md;B(h.key?h.key:"",m+0,32);B(h.code?h.code:"",m+32,32);p[m+64>>2]=h.location;p[m+68>>2]=h.ctrlKey;p[m+72>>2]=h.shiftKey;p[m+76>>2]=h.altKey;p[m+80>>2]=h.metaKey;p[m+84>>2]=h.repeat;B(h.locale?h.locale:"",m+88,32);B(h.char?h.char:"",m+120,32);p[m+152>>2]=h.charCode;p[m+156>>2]=h.keyCode;p[m+160>>2]=h.which;Y(d,e,m,b)&&h.preventDefault()},re:c};W(a)}
function ke(a,b,c){p[a>>2]=b.screenX;p[a+4>>2]=b.screenY;p[a+8>>2]=b.clientX;p[a+12>>2]=b.clientY;p[a+16>>2]=b.ctrlKey;p[a+20>>2]=b.shiftKey;p[a+24>>2]=b.altKey;p[a+28>>2]=b.metaKey;oa[a+32>>1]=b.button;oa[a+34>>1]=b.buttons;var d=b.movementY||b.screenY-wd;p[a+36>>2]=b.movementX||b.screenX-vd;p[a+40>>2]=d;c=Td(c);p[a+44>>2]=b.clientX-c.left;p[a+48>>2]=b.clientY-c.top;"wheel"!==b.type&&"mousewheel"!==b.type&&(vd=b.screenX,wd=b.screenY)}
function le(a,b,c,d,e,f){nd||(nd=C(64));a=X(a);W({target:a,Ce:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,oe:f,se:d,ue:function(h){h=h||event;ke(nd,h,a);Y(d,e,nd,b)&&h.preventDefault()},re:c})}function me(a,b,c,d,e){rd||(rd=C(260));W({target:a,oe:e,se:d,ue:function(f){f=f||event;var h=rd,m=document.pointerLockElement||document.Pf||document.pg||document.og;p[h>>2]=!!m;var n=m&&m.id?m.id:"";B(Fd(m),h+4,128);B(n,h+132,128);Y(d,20,h,b)&&f.preventDefault()},re:c})}
function ne(a,b,c,d){od||(od=C(36));a=X(a);W({target:a,oe:"resize",se:d,ue:function(e){e=e||event;if(e.target==a){var f=od,h=document.body;p[f>>2]=e.detail;p[f+4>>2]=h.clientWidth;p[f+8>>2]=h.clientHeight;p[f+12>>2]=innerWidth;p[f+16>>2]=innerHeight;p[f+20>>2]=outerWidth;p[f+24>>2]=outerHeight;p[f+28>>2]=pageXOffset;p[f+32>>2]=pageYOffset;Y(d,10,f,b)&&e.preventDefault()}},re:c})}
function oe(a,b,c,d,e,f){td||(td=C(1684));a=X(a);W({target:a,Ce:"touchstart"==f||"touchend"==f,oe:f,se:d,ue:function(h){h=h||event;for(var m={},n=0;n<h.touches.length;++n){var q=h.touches[n];q.ff=!1;m[q.identifier]=q}for(n=0;n<h.changedTouches.length;++n)q=h.changedTouches[n],m[q.identifier]=q,q.ff=!0;for(n=0;n<h.targetTouches.length;++n)q=h.targetTouches[n],m[q.identifier].Sf=!0;var u=q=td;p[u+4>>2]=h.ctrlKey;p[u+8>>2]=h.shiftKey;p[u+12>>2]=h.altKey;p[u+16>>2]=h.metaKey;u+=20;var w=Td(a),D=0;for(n in m){var y=
m[n];p[u>>2]=y.identifier;p[u+4>>2]=y.screenX;p[u+8>>2]=y.screenY;p[u+12>>2]=y.clientX;p[u+16>>2]=y.clientY;p[u+20>>2]=y.pageX;p[u+24>>2]=y.pageY;p[u+28>>2]=y.ff;p[u+32>>2]=y.Sf;p[u+36>>2]=y.clientX-w.left;p[u+40>>2]=y.clientY-w.top;u+=52;if(32<=++D)break}p[q>>2]=D;Y(d,e,q,b)&&h.preventDefault()},re:c})}
function pe(a,b,c){var d=Ld[1];sd||(sd=C(8));W({target:d,oe:"visibilitychange",se:c,ue:function(e){e=e||event;var f=sd,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);p[f>>2]=document.hidden;p[f+4>>2]=h;Y(c,21,f,a)&&e.preventDefault()},re:b})}
function qe(a,b,c,d,e){function f(m){m=m||event;ke(T,m,a);v[T+64>>3]=m.wheelDeltaX||0;v[T+72>>3]=-(m.wheelDeltaY||m.wheelDelta);v[T+80>>3]=0;p[T+88>>2]=0;Y(d,9,T,b)&&m.preventDefault()}function h(m){m=m||event;var n=T;ke(n,m,a);v[n+64>>3]=m.deltaX;v[n+72>>3]=m.deltaY;v[n+80>>3]=m.deltaZ;p[n+88>>2]=m.deltaMode;Y(d,9,n,b)&&m.preventDefault()}T||(T=C(96));W({target:a,Ce:!0,oe:e,se:d,ue:"wheel"==e?h:f,re:c})}var re={};
function se(){if(!te){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in re)a[b]=re[b];var c=[];for(b in a)c.push(b+"="+a[b]);te=c}return te}var te,ue;function Db(a,b,c,d){a||(a=this);this.parent=a;this.ye=a.ye;this.Qe=null;this.id=ub++;this.name=b;this.mode=c;this.je={};this.ke={};this.Se=d}
Object.defineProperties(Db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Rb();vb=Array(4096);Kb(G,"/");H("/tmp");H("/home");H("/home/web_user");
(function(){H("/dev");jb(259,{read:function(){return 0},write:function(c,d,e,f){return f}});Mb("/dev/null",259);ib(1280,lb);ib(1536,mb);Mb("/dev/tty",1280);Mb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}b||(b=function(){x("random_device")});Ub("random",b);Ub("urandom",b);H("/dev/shm");H("/dev/shm/tmp")})();H("/proc");H("/proc/self");H("/proc/self/fd");
Kb({ye:function(){var a=ob("/proc/self","fd",16895,73);a.je={He:function(b,c){var d=tb[+c];if(!d)throw new F(8);b={parent:null,ye:{tf:"fake"},je:{Ke:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");g.requestFullscreen=function(a,b){Hc(a,b)};g.requestAnimationFrame=function(a){hc(a)};g.setCanvasSize=function(a,b,c){Jc(g.canvas,a,b);c||Kc()};g.pauseMainLoop=function(){ec=null;kc++};g.resumeMainLoop=function(){kc++;var a=bc,b=cc,c=dc;dc=null;ic(c,0,!1,jc,!0);ac(a,b);ec()};
g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Ac(a,b,c,d)};for(var J,ve=new Float32Array(256),Z=0;256>Z;Z++)hd[Z]=ve.subarray(0,Z+1);var we=new Int32Array(256);for(Z=0;256>Z;Z++)id[Z]=we.subarray(0,Z+1);for(var Be=0;32>Be;Be++)Xd.push(Array(Be));
var De={b:function(a,b,c,d){x("Assertion failed: "+z(a)+", at: "+[b?z(b):"unknown filename",c,d?z(d):"unknown function"])},o:function(a,b,c){Xb=c;try{var d=Zb(a);switch(b){case 0:var e=Yb();return 0>e?-28:Ob(d.path,d.flags,0,e).Ae;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Yb(),d.flags|=e,0;case 12:return e=Yb(),oa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return ab(),-1;default:return-28}}catch(f){return"undefined"!==typeof Wb&&f instanceof F||x(f),-f.De}},
xa:function(a,b,c){Xb=c;try{var d=Zb(a);switch(b){case 21509:case 21505:return d.me?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.me?0:-59;case 21519:if(!d.me)return-59;var e=Yb();return p[e>>2]=0;case 21520:return d.me?-28:-59;case 21531:a=e=Yb();if(!d.ke.Of)throw new F(59);return d.ke.Of(d,b,a);case 21523:return d.me?0:-59;case 21524:return d.me?0:-59;default:x("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof Wb&&f instanceof F||x(f),-f.De}},ya:function(a,
b,c){Xb=c;try{var d=z(a),e=Yb();return Ob(d,b,e).Ae}catch(f){return"undefined"!==typeof Wb&&f instanceof F||x(f),-f.De}},sa:function(){x()},h:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=$b();else return ab(),-1;p[b>>2]=a/1E3|0;p[b+4>>2]=a%1E3*1E6|0;return 0},Ca:function(){x("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},jd:function(a){if(12448==a)return K=12288,1;K=12300;return 0},Aa:function(a,b,c,d,e){if(62E3!=
a)K=12296,c=0;else{if(b)for(;;){a=p[b>>2];if(12321==a)L.alpha=0<p[b+4>>2];else if(12325==a)L.depth=0<p[b+4>>2];else if(12326==a)L.stencil=0<p[b+4>>2];else if(12337==a)a=p[b+4>>2],L.antialias=0<a;else if(12338==a)a=p[b+4>>2],L.antialias=1==a;else if(12544==a)L.qg=12547!=p[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(p[e>>2]=1),c&&0<d&&(p[c>>2]=62002),K=12288,c=1):(K=12300,c=0)}return c},rb:function(a,b,c,d){if(62E3!=a)return K=12296,0;for(a=1;;){b=p[d>>2];if(12440==b)a=p[d+4>>2];else if(12344==
b)break;else return K=12292,0;d+=8}if(2!=a)return K=12293,0;L.rf=a-1;L.rg=0;Sc=Cc(g.canvas,L);if(0!=Sc)return K=12288,Dc(Sc),g.Yf=!0,sc.forEach(function(e){e()}),Dc(null),62004;K=12297;return 0},Ob:function(a,b){if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;K=12288;return 62006},Db:function(a,b){if(62E3!=a)return K=12296,0;if(62004!=b)return K=12294,0;a=Sc;cd===I[a]&&(cd=null);if("object"===typeof Hd)for(var c=I[a].ze.canvas,d=0;d<U.length;++d)U[d].target!=c||zd(d--);I[a]&&I[a].ze.canvas&&
(I[a].ze.canvas.Ge=void 0);I[a]=null;K=12288;Oc==b&&(Oc=0);return 1},Zb:function(a,b){if(62E3!=a)return K=12296,0;if(62006!=b)return K=12301,1;Pc==b&&(Pc=0);Qc==b&&(Qc=0);K=12288;return 1},Fa:function(a,b,c,d){if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;if(!d)return K=12300,0;K=12288;switch(c){case 12320:return p[d>>2]=L.alpha?32:24,1;case 12321:return p[d>>2]=L.alpha?8:0,1;case 12322:return p[d>>2]=8,1;case 12323:return p[d>>2]=8,1;case 12324:return p[d>>2]=8,1;case 12325:return p[d>>
2]=L.depth?24:0,1;case 12326:return p[d>>2]=L.stencil?8:0,1;case 12327:return p[d>>2]=12344,1;case 12328:return p[d>>2]=62002,1;case 12329:return p[d>>2]=0,1;case 12330:return p[d>>2]=4096,1;case 12331:return p[d>>2]=16777216,1;case 12332:return p[d>>2]=4096,1;case 12333:return p[d>>2]=0,1;case 12334:return p[d>>2]=0,1;case 12335:return p[d>>2]=12344,1;case 12337:return p[d>>2]=L.antialias?4:0,1;case 12338:return p[d>>2]=L.antialias?1:0,1;case 12339:return p[d>>2]=4,1;case 12340:return p[d>>2]=12344,
1;case 12341:case 12342:case 12343:return p[d>>2]=-1,1;case 12345:case 12346:return p[d>>2]=0,1;case 12347:return p[d>>2]=0,1;case 12348:return p[d>>2]=1;case 12349:case 12350:return p[d>>2]=0,1;case 12351:return p[d>>2]=12430,1;case 12352:return p[d>>2]=4,1;case 12354:return p[d>>2]=0,1;default:return K=12292,0}},l:function(){K=12288;return 62E3},gb:function(){return K},ud:function(a){return Ce(a)},ia:function(a,b,c){if(62E3==a)return b&&(p[b>>2]=1),c&&(p[c>>2]=4),Nc=!0,K=12288,1;K=12296;return 0},
ic:function(a,b,c,d){if(62E3!=a)return K=12296,0;if(0!=d&&62004!=d)return K=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return K=12301,0;Dc(d?Sc:null);Oc=d;Qc=b;Pc=c;K=12288;return 1},Xa:function(a,b){if(62E3!=a)return K=12296,0;K=12288;if(Rc[b])return Rc[b];switch(b){case 12371:a=Ca("Emscripten");break;case 12372:a=Ca("1.4 Emscripten EGL");break;case 12373:a=Ca("");break;case 12429:a=Ca("OpenGL_ES");break;default:return K=12300,0}return Rc[b]=a},tc:function(){if(Nc)if(g.ve)if(g.ve.isContextLost())K=
12302;else return K=12288,1;else K=12290;else K=12289;return 0},Ec:function(a,b){if(62E3!=a)return K=12296,0;0==b?ac(0,0):ac(1,b);K=12288;return 1},ta:function(a){if(62E3!=a)return K=12296,0;Qc=Pc=Oc=0;Nc=!1;K=12288;return 1},_c:function(){K=12288;return 1},Pc:function(){K=12288;return 1},a:function(a,b,c){ue||(ue=[]);var d=ue;d.length=0;for(var e;e=A[b++];)100===e||102===e?(c=c+7&-8,d.push(v[c>>3]),c+=8):(c=c+3&-4,d.push(p[c>>2]),c+=4);return Za[a].apply(null,d)},Da:function(){if(!Gd())return-1;
Bd(Ud);var a=Ld[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ha:function(){Bd(Vd);if(document.exitPointerLock)document.exitPointerLock();else if(document.pf)document.pf();else return-1;return 0},f:function(){return devicePixelRatio},d:function(a,b,c){a=X(a);if(!a)return-4;a=Td(a);v[b>>3]=a.width;v[c>>3]=a.height;return 0},r:function(a,b){if(0>a||a>=Id.length)return-5;if(!Id[a])return-7;
Wd(b,Id[a]);return 0},Ba:function(){return Id.length},X:function(a){J.activeTexture(a)},W:function(a,b){J.attachShader(M[a],Q[b])},ma:function(a,b){J.te.beginQueryEXT(a,R[b])},V:function(a,b,c){J.bindAttribLocation(M[a],b,z(c))},U:function(a,b){J.bindBuffer(a,Yc[b])},T:function(a,b){J.bindFramebuffer(a,Zc[b])},S:function(a,b){J.bindRenderbuffer(a,$c[b])},R:function(a,b){J.bindTexture(a,ad[b])},da:function(a){J.bindVertexArray(bd[a])},Q:function(a,b,c,d){J.blendColor(a,b,c,d)},td:function(a){J.blendEquation(a)},
sd:function(a,b){J.blendEquationSeparate(a,b)},rd:function(a,b){J.blendFunc(a,b)},qd:function(a,b,c,d){J.blendFuncSeparate(a,b,c,d)},pd:function(a,b,c,d){J.bufferData(a,c?A.subarray(c,c+b):b,d)},od:function(a,b,c,d){J.bufferSubData(a,b,A.subarray(d,d+c))},nd:function(a){return J.checkFramebufferStatus(a)},md:function(a){J.clear(a)},ld:function(a,b,c,d){J.clearColor(a,b,c,d)},kd:function(a){J.clearDepth(a)},id:function(a){J.clearStencil(a)},hd:function(a,b,c,d){J.colorMask(!!a,!!b,!!c,!!d)},gd:function(a){J.compileShader(Q[a])},
fd:function(a,b,c,d,e,f,h,m){J.compressedTexImage2D(a,b,c,d,e,f,m?A.subarray(m,m+h):null)},ed:function(a,b,c,d,e,f,h,m,n){J.compressedTexSubImage2D(a,b,c,d,e,f,h,n?A.subarray(n,n+m):null)},dd:function(a,b,c,d,e,f,h,m){J.copyTexImage2D(a,b,c,d,e,f,h,m)},cd:function(a,b,c,d,e,f,h,m){J.copyTexSubImage2D(a,b,c,d,e,f,h,m)},bd:function(){var a=gd(M),b=J.createProgram();b.name=a;M[a]=b;return a},ad:function(a){var b=gd(Q);Q[b]=J.createShader(a);return b},$c:function(a){J.cullFace(a)},Zc:function(a,b){for(var c=
0;c<a;c++){var d=p[b+4*c>>2],e=Yc[d];e&&(J.deleteBuffer(e),e.name=0,Yc[d]=null,d==kd&&(kd=0),d==ld&&(ld=0))}},Yc:function(a,b){for(var c=0;c<a;++c){var d=p[b+4*c>>2],e=Zc[d];e&&(J.deleteFramebuffer(e),e.name=0,Zc[d]=null)}},Xc:function(a){if(a){var b=M[a];b?(J.deleteProgram(b),b.name=0,M[a]=null,dd[a]=null):S(1281)}},oa:function(a,b){for(var c=0;c<a;c++){var d=p[b+4*c>>2],e=R[d];e&&(J.te.deleteQueryEXT(e),R[d]=null)}},Wc:function(a,b){for(var c=0;c<a;c++){var d=p[b+4*c>>2],e=$c[d];e&&(J.deleteRenderbuffer(e),
e.name=0,$c[d]=null)}},Vc:function(a){if(a){var b=Q[a];b?(J.deleteShader(b),Q[a]=null):S(1281)}},Uc:function(a,b){for(var c=0;c<a;c++){var d=p[b+4*c>>2],e=ad[d];e&&(J.deleteTexture(e),e.name=0,ad[d]=null)}},ca:function(a,b){for(var c=0;c<a;c++){var d=p[b+4*c>>2];J.deleteVertexArray(bd[d]);bd[d]=null}},Tc:function(a){J.depthFunc(a)},Sc:function(a){J.depthMask(!!a)},Rc:function(a,b){J.depthRange(a,b)},Qc:function(a,b){J.detachShader(M[a],Q[b])},Oc:function(a){J.disable(a)},Nc:function(a){J.disableVertexAttribArray(a)},
Mc:function(a,b,c){J.drawArrays(a,b,c)},_:function(a,b,c,d){J.drawArraysInstanced(a,b,c,d)},$:function(a,b){for(var c=Xd[a],d=0;d<a;d++)c[d]=p[b+4*d>>2];J.drawBuffers(c)},Lc:function(a,b,c,d){J.drawElements(a,b,c,d)},Z:function(a,b,c,d,e){J.drawElementsInstanced(a,b,c,d,e)},Kc:function(a){J.enable(a)},Jc:function(a){J.enableVertexAttribArray(a)},la:function(a){J.te.endQueryEXT(a)},Ic:function(){J.finish()},Hc:function(){J.flush()},Gc:function(a,b,c,d){J.framebufferRenderbuffer(a,b,c,$c[d])},Fc:function(a,
b,c,d,e){J.framebufferTexture2D(a,b,c,ad[d],e)},Dc:function(a){J.frontFace(a)},Cc:function(a,b){Yd(a,b,"createBuffer",Yc)},Ac:function(a,b){Yd(a,b,"createFramebuffer",Zc)},pa:function(a,b){for(var c=0;c<a;c++){var d=J.te.createQueryEXT();if(!d){for(S(1282);c<a;)p[b+4*c++>>2]=0;break}var e=gd(R);d.name=e;R[e]=d;p[b+4*c>>2]=e}},zc:function(a,b){Yd(a,b,"createRenderbuffer",$c)},yc:function(a,b){Yd(a,b,"createTexture",ad)},ba:function(a,b){Yd(a,b,"createVertexArray",bd)},Bc:function(a){J.generateMipmap(a)},
xc:function(a,b,c,d,e,f,h){a=M[a];if(a=J.getActiveAttrib(a,b))c=0<c&&h?B(a.name,h,c):0,d&&(p[d>>2]=c),e&&(p[e>>2]=a.size),f&&(p[f>>2]=a.type)},wc:function(a,b,c,d,e,f,h){a=M[a];if(a=J.getActiveUniform(a,b))c=0<c&&h?B(a.name,h,c):0,d&&(p[d>>2]=c),e&&(p[e>>2]=a.size),f&&(p[f>>2]=a.type)},vc:function(a,b,c,d){a=J.getAttachedShaders(M[a]);var e=a.length;e>b&&(e=b);p[c>>2]=e;for(b=0;b<e;++b)p[d+4*b>>2]=Q.indexOf(a[b])},uc:function(a,b){return J.getAttribLocation(M[a],z(b))},sc:function(a,b){$d(a,b,4)},
rc:function(a,b,c){c?p[c>>2]=J.getBufferParameter(a,b):S(1281)},qc:function(){var a=J.getError()||Xc;Xc=0;return a},pc:function(a,b){$d(a,b,2)},oc:function(a,b,c,d){a=J.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;p[d>>2]=a},nc:function(a,b){$d(a,b,0)},lc:function(a,b,c,d){a=J.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(p[c>>2]=b)},mc:function(a,b,c){if(c)if(a>=Wc)S(1281);else{var d=dd[a];if(d)if(35716==
b)a=J.getProgramInfoLog(M[a]),null===a&&(a="(unknown error)"),p[c>>2]=a.length+1;else if(35719==b)p[c>>2]=d.Ye;else if(35722==b){if(-1==d.Ie){a=M[a];var e=J.getProgramParameter(a,35721);for(b=d.Ie=0;b<e;++b)d.Ie=Math.max(d.Ie,J.getActiveAttrib(a,b).name.length+1)}p[c>>2]=d.Ie}else if(35381==b){if(-1==d.Je)for(a=M[a],e=J.getProgramParameter(a,35382),b=d.Je=0;b<e;++b)d.Je=Math.max(d.Je,J.getActiveUniformBlockName(a,b).length+1);p[c>>2]=d.Je}else p[c>>2]=J.getProgramParameter(M[a],b);else S(1282)}else S(1281)},
fa:function(a,b,c){if(c){a=J.te.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Zd(c,d)}else S(1281)},ha:function(a,b,c){if(c){a=J.te.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;p[c>>2]=d}else S(1281)},ea:function(a,b,c){if(c){a=J.te.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Zd(c,d)}else S(1281)},ga:function(a,b,c){if(c){a=J.te.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;p[c>>2]=d}else S(1281)},ja:function(a,b,c){c?p[c>>
2]=J.te.getQueryEXT(a,b):S(1281)},kc:function(a,b,c){c?p[c>>2]=J.getRenderbufferParameter(a,b):S(1281)},hc:function(a,b,c,d){a=J.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(p[c>>2]=b)},gc:function(a,b,c,d){a=J.getShaderPrecisionFormat(a,b);p[c>>2]=a.rangeMin;p[c+4>>2]=a.rangeMax;p[d>>2]=a.precision},fc:function(a,b,c,d){if(a=J.getShaderSource(Q[a]))b=0<b&&d?B(a,d,b):0,c&&(p[c>>2]=b)},jc:function(a,b,c){c?35716==b?(a=J.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),
p[c>>2]=a.length+1):35720==b?(a=J.getShaderSource(Q[a]),p[c>>2]=null===a||0==a.length?0:a.length+1):p[c>>2]=J.getShaderParameter(Q[a],b):S(1281)},ec:function(a){if(ed[a])return ed[a];switch(a){case 7939:var b=J.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ae(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=J.getParameter(a))||S(1280);b=ae(b);break;case 7938:b=ae("OpenGL ES 2.0 ("+J.getParameter(7938)+")");break;case 35724:b=J.getParameter(35724);var c=
b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ae(b);break;default:return S(1280),0}return ed[a]=b},dc:function(a,b,c){c?t[c>>2]=J.getTexParameter(a,b):S(1281)},cc:function(a,b,c){c?p[c>>2]=J.getTexParameter(a,b):S(1281)},$b:function(a,b){b=z(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=dd[a]&&dd[a].Af[b])&&0<=c&&c<a[0]?a[1]+c:-1},bc:function(a,
b,c){be(a,b,c,2)},ac:function(a,b,c){be(a,b,c,0)},Xb:function(a,b,c){c?p[c>>2]=J.getVertexAttribOffset(a,b):S(1281)},_b:function(a,b,c){ce(a,b,c,2)},Yb:function(a,b,c){ce(a,b,c,5)},Wb:function(a,b){J.hint(a,b)},Vb:function(a){return(a=Yc[a])?J.isBuffer(a):0},Ub:function(a){return J.isEnabled(a)},Tb:function(a){return(a=Zc[a])?J.isFramebuffer(a):0},Sb:function(a){return(a=M[a])?J.isProgram(a):0},na:function(a){return(a=R[a])?J.te.isQueryEXT(a):0},Rb:function(a){return(a=$c[a])?J.isRenderbuffer(a):
0},Qb:function(a){return(a=Q[a])?J.isShader(a):0},Pb:function(a){return(a=ad[a])?J.isTexture(a):0},aa:function(a){return(a=bd[a])?J.isVertexArray(a):0},Nb:function(a){J.lineWidth(a)},Mb:function(a){J.linkProgram(M[a]);var b=M[a];a=dd[a]={Af:{},Ye:0,Ie:-1,Je:-1};for(var c=a.Af,d=J.getProgramParameter(b,35718),e=0;e<d;++e){var f=J.getActiveUniform(b,e),h=f.name;a.Ye=Math.max(a.Ye,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=J.getUniformLocation(b,h);if(m){var n=gd(N);c[h]=[f.size,
n];N[n]=m;for(var q=1;q<f.size;++q)m=J.getUniformLocation(b,h+"["+q+"]"),n=gd(N),N[n]=m}}},Lb:function(a,b){3317==a&&(fd=b);J.pixelStorei(a,b)},Kb:function(a,b){J.polygonOffset(a,b)},ka:function(a,b){J.te.queryCounterEXT(R[a],b)},Jb:function(a,b,c,d,e,f,h){(h=de(f,e,c,d,h))?J.readPixels(a,b,c,d,e,f,h):S(1280)},Ib:function(){},Hb:function(a,b,c,d){J.renderbufferStorage(a,b,c,d)},Gb:function(a,b){J.sampleCoverage(a,!!b)},Fb:function(a,b,c,d){J.scissor(a,b,c,d)},Eb:function(){S(1280)},Cb:function(a,
b,c,d){for(var e="",f=0;f<b;++f){var h=d?p[d+4*f>>2]:-1;e+=z(p[c+4*f>>2],0>h?void 0:h)}J.shaderSource(Q[a],e)},Bb:function(a,b,c){J.stencilFunc(a,b,c)},Ab:function(a,b,c,d){J.stencilFuncSeparate(a,b,c,d)},zb:function(a){J.stencilMask(a)},yb:function(a,b){J.stencilMaskSeparate(a,b)},xb:function(a,b,c){J.stencilOp(a,b,c)},wb:function(a,b,c,d){J.stencilOpSeparate(a,b,c,d)},vb:function(a,b,c,d,e,f,h,m,n){J.texImage2D(a,b,c,d,e,f,h,m,n?de(m,h,d,e,n):null)},ub:function(a,b,c){J.texParameterf(a,b,c)},tb:function(a,
b,c){J.texParameterf(a,b,t[c>>2])},qb:function(a,b,c){J.texParameteri(a,b,c)},pb:function(a,b,c){J.texParameteri(a,b,p[c>>2])},ob:function(a,b,c,d,e,f,h,m,n){var q=null;n&&(q=de(m,h,e,f,n));J.texSubImage2D(a,b,c,d,e,f,h,m,q)},nb:function(a,b){J.uniform1f(N[a],b)},mb:function(a,b,c){if(256>=b)for(var d=hd[b-1],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);J.uniform1fv(N[a],d)},lb:function(a,b){J.uniform1i(N[a],b)},kb:function(a,b,c){if(256>=b)for(var d=id[b-1],e=0;e<b;++e)d[e]=p[c+
4*e>>2];else d=p.subarray(c>>2,c+4*b>>2);J.uniform1iv(N[a],d)},jb:function(a,b,c){J.uniform2f(N[a],b,c)},ib:function(a,b,c){if(256>=2*b)for(var d=hd[2*b-1],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);J.uniform2fv(N[a],d)},hb:function(a,b,c){J.uniform2i(N[a],b,c)},fb:function(a,b,c){if(256>=2*b)for(var d=id[2*b-1],e=0;e<2*b;e+=2)d[e]=p[c+4*e>>2],d[e+1]=p[c+(4*e+4)>>2];else d=p.subarray(c>>2,c+8*b>>2);J.uniform2iv(N[a],d)},eb:function(a,b,c,d){J.uniform3f(N[a],
b,c,d)},db:function(a,b,c){if(256>=3*b)for(var d=hd[3*b-1],e=0;e<3*b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);J.uniform3fv(N[a],d)},cb:function(a,b,c,d){J.uniform3i(N[a],b,c,d)},bb:function(a,b,c){if(256>=3*b)for(var d=id[3*b-1],e=0;e<3*b;e+=3)d[e]=p[c+4*e>>2],d[e+1]=p[c+(4*e+4)>>2],d[e+2]=p[c+(4*e+8)>>2];else d=p.subarray(c>>2,c+12*b>>2);J.uniform3iv(N[a],d)},ab:function(a,b,c,d,e){J.uniform4f(N[a],b,c,d,e)},$a:function(a,b,c){if(256>=
4*b){var d=hd[4*b-1],e=t;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=t.subarray(c>>2,c+16*b>>2);J.uniform4fv(N[a],d)},_a:function(a,b,c,d,e){J.uniform4i(N[a],b,c,d,e)},Za:function(a,b,c){if(256>=4*b)for(var d=id[4*b-1],e=0;e<4*b;e+=4)d[e]=p[c+4*e>>2],d[e+1]=p[c+(4*e+4)>>2],d[e+2]=p[c+(4*e+8)>>2],d[e+3]=p[c+(4*e+12)>>2];else d=p.subarray(c>>2,c+16*b>>2);J.uniform4iv(N[a],d)},Ya:function(a,b,c,d){if(256>=4*b)for(var e=hd[4*b-1],f=0;f<4*b;f+=4)e[f]=
t[d+4*f>>2],e[f+1]=t[d+(4*f+4)>>2],e[f+2]=t[d+(4*f+8)>>2],e[f+3]=t[d+(4*f+12)>>2];else e=t.subarray(d>>2,d+16*b>>2);J.uniformMatrix2fv(N[a],!!c,e)},Wa:function(a,b,c,d){if(256>=9*b)for(var e=hd[9*b-1],f=0;f<9*b;f+=9)e[f]=t[d+4*f>>2],e[f+1]=t[d+(4*f+4)>>2],e[f+2]=t[d+(4*f+8)>>2],e[f+3]=t[d+(4*f+12)>>2],e[f+4]=t[d+(4*f+16)>>2],e[f+5]=t[d+(4*f+20)>>2],e[f+6]=t[d+(4*f+24)>>2],e[f+7]=t[d+(4*f+28)>>2],e[f+8]=t[d+(4*f+32)>>2];else e=t.subarray(d>>2,d+36*b>>2);J.uniformMatrix3fv(N[a],!!c,e)},Va:function(a,
b,c,d){if(256>=16*b){var e=hd[16*b-1],f=t;d>>=2;for(var h=0;h<16*b;h+=16){var m=d+h;e[h]=f[m];e[h+1]=f[m+1];e[h+2]=f[m+2];e[h+3]=f[m+3];e[h+4]=f[m+4];e[h+5]=f[m+5];e[h+6]=f[m+6];e[h+7]=f[m+7];e[h+8]=f[m+8];e[h+9]=f[m+9];e[h+10]=f[m+10];e[h+11]=f[m+11];e[h+12]=f[m+12];e[h+13]=f[m+13];e[h+14]=f[m+14];e[h+15]=f[m+15]}}else e=t.subarray(d>>2,d+64*b>>2);J.uniformMatrix4fv(N[a],!!c,e)},Ua:function(a){J.useProgram(M[a])},Ta:function(a){J.validateProgram(M[a])},Sa:function(a,b){J.vertexAttrib1f(a,b)},Ra:function(a,
b){J.vertexAttrib1f(a,t[b>>2])},Qa:function(a,b,c){J.vertexAttrib2f(a,b,c)},Pa:function(a,b){J.vertexAttrib2f(a,t[b>>2],t[b+4>>2])},Oa:function(a,b,c,d){J.vertexAttrib3f(a,b,c,d)},Na:function(a,b){J.vertexAttrib3f(a,t[b>>2],t[b+4>>2],t[b+8>>2])},Ma:function(a,b,c,d,e){J.vertexAttrib4f(a,b,c,d,e)},La:function(a,b){J.vertexAttrib4f(a,t[b>>2],t[b+4>>2],t[b+8>>2],t[b+12>>2])},Y:function(a,b){J.vertexAttribDivisor(a,b)},Ka:function(a,b,c,d,e,f){J.vertexAttribPointer(a,b,c,!!d,e,f)},Ja:function(a,b,c,d){J.viewport(a,
b,c,d)},k:function(){return 0},qa:function(a,b,c){A.copyWithin(a,b,b+c)},Ea:function(a,b,c){return ee(a,{af:p[c>>2],Ve:p[c+4>>2],Jf:p[c+8>>2],Gf:b,Ne:p[c+12>>2],ef:p[c+16>>2]})},N:function(a,b){a=X(a);return a?a.requestPointerLock||a.Re?Dd&&Ed.Ce?Vd(a):b?(Ad(Vd,2,[a]),1):-2:-1:-4},ra:function(){x("OOM")},s:function(){return(Id=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},t:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;
if(1!==c)return-5;fe(a,b);return 0},F:function(a,b,c,d){ge(a,b,c,d,12,"blur");return 0},e:Pd,i:function(a,b,c){a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},G:function(a,b,c,d){ge(a,b,c,d,13,"focus");return 0},w:function(a,b,c,d){if(!Gd())return-1;a=X(a);if(!a)return-4;he(a,b,c,d,"fullscreenchange");he(a,b,c,d,"webkitfullscreenchange");return 0},q:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;ie(a,b,c,26,"gamepadconnected");return 0},
p:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;ie(a,b,c,27,"gamepaddisconnected");return 0},z:function(a,b,c,d){je(a,b,c,d,2,"keydown");return 0},x:function(a,b,c,d){je(a,b,c,d,1,"keypress");return 0},y:function(a,b,c,d){je(a,b,c,d,3,"keyup");return 0},sb:ic,L:function(a,b,c,d){le(a,b,c,d,5,"mousedown");return 0},J:function(a,b,c,d){le(a,b,c,d,33,"mouseenter");return 0},I:function(a,b,c,d){le(a,b,c,d,34,"mouseleave");return 0},M:function(a,b,c,d){le(a,b,c,d,8,"mousemove");
return 0},K:function(a,b,c,d){le(a,b,c,d,6,"mouseup");return 0},A:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.pf||document.body.Pf||document.body.Re))return-1;a=X(a);if(!a)return-4;me(a,b,c,d,"pointerlockchange");me(a,b,c,d,"mozpointerlockchange");me(a,b,c,d,"webkitpointerlockchange");me(a,b,c,d,"mspointerlockchange");return 0},v:function(a,b,c,d){ne(a,b,c,d);return 0},B:function(a,b,c,d){oe(a,b,c,d,25,"touchcancel");return 0},D:function(a,b,c,
d){oe(a,b,c,d,23,"touchend");return 0},C:function(a,b,c,d){oe(a,b,c,d,24,"touchmove");return 0},E:function(a,b,c,d){oe(a,b,c,d,22,"touchstart");return 0},u:function(a,b,c){pe(a,b,c);return 0},H:function(a,b,c,d){a=X(a);return"undefined"!==typeof a.onwheel?(qe(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(qe(a,b,c,d,"mousewheel"),0):-1},j:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},ua:function(a,b){var c=
0;se().forEach(function(d,e){var f=b+c;e=p[a+4*e>>2]=f;for(f=0;f<d.length;++f)l[e++>>0]=d.charCodeAt(f);l[e>>0]=0;c+=d.length+1});return 0},va:function(a,b){var c=se();p[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});p[b>>2]=d;return 0},n:function(a){try{var b=Zb(a);if(null===b.Ae)throw new F(8);b.Xe&&(b.Xe=null);try{b.ke.close&&b.ke.close(b)}catch(c){throw c;}finally{tb[b.Ae]=null}b.Ae=null;return 0}catch(c){return"undefined"!==typeof Wb&&c instanceof F||x(c),c.De}},wa:function(a,b,
c,d){try{a:{for(var e=Zb(a),f=a=0;f<c;f++){var h=p[b+(8*f+4)>>2],m=e,n=p[b+8*f>>2],q=h,u=void 0,w=l;if(0>q||0>u)throw new F(28);if(null===m.Ae)throw new F(8);if(1===(m.flags&2097155))throw new F(8);if(16384===(m.node.mode&61440))throw new F(31);if(!m.ke.read)throw new F(28);var D="undefined"!==typeof u;if(!D)u=m.position;else if(!m.seekable)throw new F(70);var y=m.ke.read(m,w,n,q,u);D||(m.position+=y);var O=y;if(0>O){var P=-1;break a}a+=O;if(O<h)break}P=a}p[d>>2]=P;return 0}catch(Ya){return"undefined"!==
typeof Wb&&Ya instanceof F||x(Ya),Ya.De}},Ia:function(a,b,c,d,e){try{var f=Zb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Qb(f,a,d);pa=[f.position>>>0,(r=f.position,1<=+qa(r)?0<r?(ra(+sa(r/4294967296),4294967295)|0)>>>0:~~+ta((r-+(~~r>>>0))/4294967296)>>>0:0)];p[e>>2]=pa[0];p[e+4>>2]=pa[1];f.Xe&&0===a&&0===d&&(f.Xe=null);return 0}catch(h){return"undefined"!==typeof Wb&&h instanceof F||x(h),h.De}},m:function(a,b,c,d){try{a:{for(var e=Zb(a),f=a=0;f<c;f++){var h=
e,m=p[b+8*f>>2],n=p[b+(8*f+4)>>2],q=void 0,u=l;if(0>n||0>q)throw new F(28);if(null===h.Ae)throw new F(8);if(0===(h.flags&2097155))throw new F(8);if(16384===(h.node.mode&61440))throw new F(31);if(!h.ke.write)throw new F(28);h.seekable&&h.flags&1024&&Qb(h,0,2);var w="undefined"!==typeof q;if(!w)q=h.position;else if(!h.seekable)throw new F(70);var D=h.ke.write(h,u,m,n,q,void 0);w||(h.position+=D);try{if(h.path&&xb.onWriteToFile)xb.onWriteToFile(h.path)}catch(P){k("FS.trackingDelegate['onWriteToFile']('"+
h.path+"') threw an exception: "+P.message)}var y=D;if(0>y){var O=-1;break a}a+=y}O=a}p[d>>2]=O;return 0}catch(P){return"undefined"!==typeof Wb&&P instanceof F||x(P),P.De}},g:function(a){var b=Date.now();p[a>>2]=b/1E3|0;p[a+4>>2]=b%1E3*1E3|0;return 0},memory:ua,za:function(a,b){if(0===a)return ab(),-1;var c=p[a>>2];a=p[a+4>>2];if(0>a||999999999<a||0>c)return ab(),-1;0!==b&&(p[b>>2]=0,p[b+4>>2]=0);b=1E6*c+a/1E3;for(c=$b();$b()-c<b/1E3;);},P:function(a){a=+a;return 0<=a?+sa(a+.5):+ta(a-.5)},O:function(){},
c:function(){return 0},Ga:function(){return 0},table:va},Ee=function(){function a(e){g.asm=e.exports;Qa--;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa&&(e=Sa,Sa=null,e()))}function b(e){a(e.instance)}function c(e){return Xa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);x(f)})}var d={a:De};Qa++;g.monitorRunDependencies&&g.monitorRunDependencies(Qa);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(ma||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||"function"!==typeof fetch)return c(b);fetch(Ua,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();g.asm=Ee;
var $a=g.___wasm_call_ctors=function(){return($a=g.___wasm_call_ctors=g.asm.vd).apply(null,arguments)};g._main=function(){return(g._main=g.asm.wd).apply(null,arguments)};
var C=g._malloc=function(){return(C=g._malloc=g.asm.xd).apply(null,arguments)},bb=g.___errno_location=function(){return(bb=g.___errno_location=g.asm.yd).apply(null,arguments)},Ce=g._emscripten_GetProcAddress=function(){return(Ce=g._emscripten_GetProcAddress=g.asm.zd).apply(null,arguments)},Nd=g.stackSave=function(){return(Nd=g.stackSave=g.asm.Ad).apply(null,arguments)},Ea=g.stackAlloc=function(){return(Ea=g.stackAlloc=g.asm.Bd).apply(null,arguments)},Od=g.stackRestore=function(){return(Od=g.stackRestore=
g.asm.Cd).apply(null,arguments)};g.dynCall_v=function(){return(g.dynCall_v=g.asm.Dd).apply(null,arguments)};g.dynCall_vi=function(){return(g.dynCall_vi=g.asm.Ed).apply(null,arguments)};g.dynCall_viiii=function(){return(g.dynCall_viiii=g.asm.Fd).apply(null,arguments)};g.dynCall_iiiii=function(){return(g.dynCall_iiiii=g.asm.Gd).apply(null,arguments)};g.dynCall_ii=function(){return(g.dynCall_ii=g.asm.Hd).apply(null,arguments)};
var Y=g.dynCall_iiii=function(){return(Y=g.dynCall_iiii=g.asm.Id).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Jd).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Kd).apply(null,arguments)};g.dynCall_iii=function(){return(g.dynCall_iii=g.asm.Ld).apply(null,arguments)};g.dynCall_vii=function(){return(g.dynCall_vii=g.asm.Md).apply(null,arguments)};g.dynCall_iiiiii=function(){return(g.dynCall_iiiiii=g.asm.Nd).apply(null,arguments)};
g.dynCall_iiiiiiiiii=function(){return(g.dynCall_iiiiiiiiii=g.asm.Od).apply(null,arguments)};g.dynCall_iiiiiidii=function(){return(g.dynCall_iiiiiidii=g.asm.Pd).apply(null,arguments)};g.dynCall_iiiiiiiii=function(){return(g.dynCall_iiiiiiiii=g.asm.Qd).apply(null,arguments)};g.dynCall_viiiiiii=function(){return(g.dynCall_viiiiiii=g.asm.Rd).apply(null,arguments)};g.dynCall_viiiiiiiiiii=function(){return(g.dynCall_viiiiiiiiiii=g.asm.Sd).apply(null,arguments)};
g.dynCall_iiiiiiii=function(){return(g.dynCall_iiiiiiii=g.asm.Td).apply(null,arguments)};g.dynCall_i=function(){return(g.dynCall_i=g.asm.Ud).apply(null,arguments)};g.dynCall_viii=function(){return(g.dynCall_viii=g.asm.Vd).apply(null,arguments)};g.dynCall_iidiiii=function(){return(g.dynCall_iidiiii=g.asm.Wd).apply(null,arguments)};g.dynCall_viiiii=function(){return(g.dynCall_viiiii=g.asm.Xd).apply(null,arguments)};g.dynCall_vffff=function(){return(g.dynCall_vffff=g.asm.Yd).apply(null,arguments)};
g.dynCall_vf=function(){return(g.dynCall_vf=g.asm.Zd).apply(null,arguments)};g.dynCall_viiiiiiii=function(){return(g.dynCall_viiiiiiii=g.asm._d).apply(null,arguments)};g.dynCall_viiiiiiiii=function(){return(g.dynCall_viiiiiiiii=g.asm.$d).apply(null,arguments)};g.dynCall_vff=function(){return(g.dynCall_vff=g.asm.ae).apply(null,arguments)};g.dynCall_vfi=function(){return(g.dynCall_vfi=g.asm.be).apply(null,arguments)};g.dynCall_viif=function(){return(g.dynCall_viif=g.asm.ce).apply(null,arguments)};
g.dynCall_vif=function(){return(g.dynCall_vif=g.asm.de).apply(null,arguments)};g.dynCall_viff=function(){return(g.dynCall_viff=g.asm.ee).apply(null,arguments)};g.dynCall_vifff=function(){return(g.dynCall_vifff=g.asm.fe).apply(null,arguments)};g.dynCall_viffff=function(){return(g.dynCall_viffff=g.asm.ge).apply(null,arguments)};g.dynCall_viiiiii=function(){return(g.dynCall_viiiiii=g.asm.he).apply(null,arguments)};g.asm=Ee;var Fe;
function pc(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function Ge(){Fe||He();Fe||(Sa=Ge)};
function He(a){function b(){if(!Fe&&(Fe=!0,g.calledRun=!0,!wa)){g.noFSInit||Sb||(Sb=!0,Rb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Ub("stdin",g.stdin):Nb("/dev/tty","/dev/stdin"),g.stdout?Ub("stdout",null,g.stdout):Nb("/dev/tty","/dev/stdout"),g.stderr?Ub("stderr",null,g.stderr):Nb("/dev/tty1","/dev/stderr"),Ob("/dev/stdin","r"),Ob("/dev/stdout","w"),Ob("/dev/stderr","w"));Ja(La);wb=!1;Ja(Ma);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ie){var c=a,d=g._main;c=c||[];
var e=c.length+1,f=Ea(4*(e+1));p[f>>2]=Da(da);for(var h=1;h<e;h++)p[(f>>2)+h]=Da(c[h-1]);p[(f>>2)+e]=0;try{var m=d(e,f);if(!noExitRuntime||0!==m){if(!noExitRuntime&&(wa=!0,g.onExit))g.onExit(m);ea(m,new pc(m))}}catch(n){n instanceof pc||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Oa.unshift(c);Ja(Oa)}}a=a||
ca;if(!(0<Qa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Pa();Ja(Ka);0<Qa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=He;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ie=!0;g.noInitialRun&&(Ie=!1);noExitRuntime=!0;He();
